[package]
name = "elf-viz"
version = "0.1.0"
authors = ["wakame-tech"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
elf = "0.0.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s"
